// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: Trafficinformation.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BandwithRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwithRequest) Reset() {
	*x = BandwithRequest{}
	mi := &file_Trafficinformation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwithRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwithRequest) ProtoMessage() {}

func (x *BandwithRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Trafficinformation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwithRequest.ProtoReflect.Descriptor instead.
func (*BandwithRequest) Descriptor() ([]byte, []int) {
	return file_Trafficinformation_proto_rawDescGZIP(), []int{0}
}

type DailyTrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyTrafficRequest) Reset() {
	*x = DailyTrafficRequest{}
	mi := &file_Trafficinformation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTrafficRequest) ProtoMessage() {}

func (x *DailyTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Trafficinformation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyTrafficRequest.ProtoReflect.Descriptor instead.
func (*DailyTrafficRequest) Descriptor() ([]byte, []int) {
	return file_Trafficinformation_proto_rawDescGZIP(), []int{1}
}

type BandwithResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bandwith      string                 `protobuf:"bytes,1,opt,name=Bandwith,proto3" json:"Bandwith,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwithResponse) Reset() {
	*x = BandwithResponse{}
	mi := &file_Trafficinformation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwithResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwithResponse) ProtoMessage() {}

func (x *BandwithResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Trafficinformation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwithResponse.ProtoReflect.Descriptor instead.
func (*BandwithResponse) Descriptor() ([]byte, []int) {
	return file_Trafficinformation_proto_rawDescGZIP(), []int{2}
}

func (x *BandwithResponse) GetBandwith() string {
	if x != nil {
		return x.Bandwith
	}
	return ""
}

type DailyTrafficResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyTraffic  string                 `protobuf:"bytes,1,opt,name=daily_traffic,json=dailyTraffic,proto3" json:"daily_traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyTrafficResponse) Reset() {
	*x = DailyTrafficResponse{}
	mi := &file_Trafficinformation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyTrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTrafficResponse) ProtoMessage() {}

func (x *DailyTrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Trafficinformation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyTrafficResponse.ProtoReflect.Descriptor instead.
func (*DailyTrafficResponse) Descriptor() ([]byte, []int) {
	return file_Trafficinformation_proto_rawDescGZIP(), []int{3}
}

func (x *DailyTrafficResponse) GetDailyTraffic() string {
	if x != nil {
		return x.DailyTraffic
	}
	return ""
}

var File_Trafficinformation_proto protoreflect.FileDescriptor

const file_Trafficinformation_proto_rawDesc = "" +
	"\n" +
	"\x18Trafficinformation.proto\x12\x15trafficinformation.v1\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fBandwithRequest\"\x15\n" +
	"\x13DailyTrafficRequest\".\n" +
	"\x10BandwithResponse\x12\x1a\n" +
	"\bBandwith\x18\x01 \x01(\tR\bBandwith\";\n" +
	"\x14DailyTrafficResponse\x12#\n" +
	"\rdaily_traffic\x18\x01 \x01(\tR\fdailyTraffic2\xac\x02\n" +
	"\x12trafficinformation\x12\x85\x01\n" +
	"\fGetBandwidth\x12&.trafficinformation.v1.BandwithRequest\x1a'.trafficinformation.v1.BandwithResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/trafficinformation/bandwith\x12\x8d\x01\n" +
	"\x0fGetDailyTraffic\x12*.trafficinformation.v1.DailyTrafficRequest\x1a+.trafficinformation.v1.DailyTrafficResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/trafficinformation/dailyB5Z3KratosBaseMicroservice/api/trafficinformation/v1;v1b\x06proto3"

var (
	file_Trafficinformation_proto_rawDescOnce sync.Once
	file_Trafficinformation_proto_rawDescData []byte
)

func file_Trafficinformation_proto_rawDescGZIP() []byte {
	file_Trafficinformation_proto_rawDescOnce.Do(func() {
		file_Trafficinformation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Trafficinformation_proto_rawDesc), len(file_Trafficinformation_proto_rawDesc)))
	})
	return file_Trafficinformation_proto_rawDescData
}

var file_Trafficinformation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Trafficinformation_proto_goTypes = []any{
	(*BandwithRequest)(nil),      // 0: trafficinformation.v1.BandwithRequest
	(*DailyTrafficRequest)(nil),  // 1: trafficinformation.v1.DailyTrafficRequest
	(*BandwithResponse)(nil),     // 2: trafficinformation.v1.BandwithResponse
	(*DailyTrafficResponse)(nil), // 3: trafficinformation.v1.DailyTrafficResponse
}
var file_Trafficinformation_proto_depIdxs = []int32{
	0, // 0: trafficinformation.v1.trafficinformation.GetBandwidth:input_type -> trafficinformation.v1.BandwithRequest
	1, // 1: trafficinformation.v1.trafficinformation.GetDailyTraffic:input_type -> trafficinformation.v1.DailyTrafficRequest
	2, // 2: trafficinformation.v1.trafficinformation.GetBandwidth:output_type -> trafficinformation.v1.BandwithResponse
	3, // 3: trafficinformation.v1.trafficinformation.GetDailyTraffic:output_type -> trafficinformation.v1.DailyTrafficResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Trafficinformation_proto_init() }
func file_Trafficinformation_proto_init() {
	if File_Trafficinformation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Trafficinformation_proto_rawDesc), len(file_Trafficinformation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Trafficinformation_proto_goTypes,
		DependencyIndexes: file_Trafficinformation_proto_depIdxs,
		MessageInfos:      file_Trafficinformation_proto_msgTypes,
	}.Build()
	File_Trafficinformation_proto = out.File
	file_Trafficinformation_proto_goTypes = nil
	file_Trafficinformation_proto_depIdxs = nil
}
