// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: trafficInformation/v1/TrafficInformation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trafficinformation_GetBandwidth_FullMethodName    = "/trafficinformation.v1.trafficinformation/GetBandwidth"
	Trafficinformation_GetDailyTraffic_FullMethodName = "/trafficinformation.v1.trafficinformation/GetDailyTraffic"
)

// TrafficinformationClient is the client API for Trafficinformation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficinformationClient interface {
	GetBandwidth(ctx context.Context, in *BandwithRequest, opts ...grpc.CallOption) (*BandwithResponse, error)
	GetDailyTraffic(ctx context.Context, in *DailyTrafficRequest, opts ...grpc.CallOption) (*DailyTrafficResponse, error)
}

type trafficinformationClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficinformationClient(cc grpc.ClientConnInterface) TrafficinformationClient {
	return &trafficinformationClient{cc}
}

func (c *trafficinformationClient) GetBandwidth(ctx context.Context, in *BandwithRequest, opts ...grpc.CallOption) (*BandwithResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BandwithResponse)
	err := c.cc.Invoke(ctx, Trafficinformation_GetBandwidth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficinformationClient) GetDailyTraffic(ctx context.Context, in *DailyTrafficRequest, opts ...grpc.CallOption) (*DailyTrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyTrafficResponse)
	err := c.cc.Invoke(ctx, Trafficinformation_GetDailyTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficinformationServer is the server API for Trafficinformation service.
// All implementations should embed UnimplementedTrafficinformationServer
// for forward compatibility.
type TrafficinformationServer interface {
	GetBandwidth(context.Context, *BandwithRequest) (*BandwithResponse, error)
	GetDailyTraffic(context.Context, *DailyTrafficRequest) (*DailyTrafficResponse, error)
}

// UnimplementedTrafficinformationServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficinformationServer struct{}

func (UnimplementedTrafficinformationServer) GetBandwidth(context.Context, *BandwithRequest) (*BandwithResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBandwidth not implemented")
}
func (UnimplementedTrafficinformationServer) GetDailyTraffic(context.Context, *DailyTrafficRequest) (*DailyTrafficResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyTraffic not implemented")
}
func (UnimplementedTrafficinformationServer) testEmbeddedByValue() {}

// UnsafeTrafficinformationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficinformationServer will
// result in compilation errors.
type UnsafeTrafficinformationServer interface {
	mustEmbedUnimplementedTrafficinformationServer()
}

func RegisterTrafficinformationServer(s grpc.ServiceRegistrar, srv TrafficinformationServer) {
	// If the following call panics, it indicates UnimplementedTrafficinformationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trafficinformation_ServiceDesc, srv)
}

func _Trafficinformation_GetBandwidth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BandwithRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficinformationServer).GetBandwidth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trafficinformation_GetBandwidth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficinformationServer).GetBandwidth(ctx, req.(*BandwithRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trafficinformation_GetDailyTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DailyTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficinformationServer).GetDailyTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trafficinformation_GetDailyTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficinformationServer).GetDailyTraffic(ctx, req.(*DailyTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trafficinformation_ServiceDesc is the grpc.ServiceDesc for Trafficinformation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trafficinformation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trafficinformation.v1.trafficinformation",
	HandlerType: (*TrafficinformationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBandwidth",
			Handler:    _Trafficinformation_GetBandwidth_Handler,
		},
		{
			MethodName: "GetDailyTraffic",
			Handler:    _Trafficinformation_GetDailyTraffic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trafficInformation/v1/TrafficInformation.proto",
}
