// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: trafficInformation/v1/TrafficInformation.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTrafficinformationGetBandwidth = "/trafficinformation.v1.trafficinformation/GetBandwidth"
const OperationTrafficinformationGetDailyTraffic = "/trafficinformation.v1.trafficinformation/GetDailyTraffic"

type TrafficinformationHTTPServer interface {
	GetBandwidth(context.Context, *BandwithRequest) (*BandwithResponse, error)
	GetDailyTraffic(context.Context, *DailyTrafficRequest) (*DailyTrafficResponse, error)
}

func RegisterTrafficinformationHTTPServer(s *http.Server, srv TrafficinformationHTTPServer) {
	r := s.Route("/")
	r.GET("/trafficinformation/bandwith", _Trafficinformation_GetBandwidth0_HTTP_Handler(srv))
	r.GET("/trafficinformation/daily", _Trafficinformation_GetDailyTraffic0_HTTP_Handler(srv))
}

func _Trafficinformation_GetBandwidth0_HTTP_Handler(srv TrafficinformationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BandwithRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTrafficinformationGetBandwidth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBandwidth(ctx, req.(*BandwithRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BandwithResponse)
		return ctx.Result(200, reply)
	}
}

func _Trafficinformation_GetDailyTraffic0_HTTP_Handler(srv TrafficinformationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DailyTrafficRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTrafficinformationGetDailyTraffic)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDailyTraffic(ctx, req.(*DailyTrafficRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DailyTrafficResponse)
		return ctx.Result(200, reply)
	}
}

type TrafficinformationHTTPClient interface {
	GetBandwidth(ctx context.Context, req *BandwithRequest, opts ...http.CallOption) (rsp *BandwithResponse, err error)
	GetDailyTraffic(ctx context.Context, req *DailyTrafficRequest, opts ...http.CallOption) (rsp *DailyTrafficResponse, err error)
}

type TrafficinformationHTTPClientImpl struct {
	cc *http.Client
}

func NewTrafficinformationHTTPClient(client *http.Client) TrafficinformationHTTPClient {
	return &TrafficinformationHTTPClientImpl{client}
}

func (c *TrafficinformationHTTPClientImpl) GetBandwidth(ctx context.Context, in *BandwithRequest, opts ...http.CallOption) (*BandwithResponse, error) {
	var out BandwithResponse
	pattern := "/trafficinformation/bandwith"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTrafficinformationGetBandwidth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TrafficinformationHTTPClientImpl) GetDailyTraffic(ctx context.Context, in *DailyTrafficRequest, opts ...http.CallOption) (*DailyTrafficResponse, error) {
	var out DailyTrafficResponse
	pattern := "/trafficinformation/daily"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTrafficinformationGetDailyTraffic))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
