// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http./middleware.
const _ = http1.SupportPackageIsVersion1

type TrafficinformationHTTPServer interface {
	GetBandwidth(context.Context, *BandwithRequest) (*BandwithResponse, error)

	GetDailyTraffic(context.Context, *DailyTrafficRequest) (*DailyTrafficResponse, error)
}

func RegisterTrafficinformationHTTPServer(s http1.ServiceRegistrar, srv TrafficinformationHTTPServer) {
	s.RegisterService(&_HTTP_Trafficinformation_serviceDesc, srv)
}

func _HTTP_Trafficinformation_GetBandwidth_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in BandwithRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficinformationServer).GetBandwidth(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Trafficinformation_GetDailyTraffic_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in DailyTrafficRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficinformationServer).GetDailyTraffic(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_Trafficinformation_serviceDesc = http1.ServiceDesc{
	ServiceName: "trafficinformation.v1.trafficinformation",
	Methods: []http1.MethodDesc{

		{
			Path:    "/trafficinformation/bandwith",
			Method:  "GET",
			Handler: _HTTP_Trafficinformation_GetBandwidth_0,
		},

		{
			Path:    "/trafficinformation/daily",
			Method:  "GET",
			Handler: _HTTP_Trafficinformation_GetDailyTraffic_0,
		},
	},
	Metadata: "Trafficinformation.proto",
}
